on:
  workflow_call:
jobs:
  ci:
    name: CI (scheduled)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: make link-dependencies
      - name: Make
        run: make ci
