on:
  workflow_call:
    inputs:
      make_target:
        required: false
        type: string
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make
        if: ${{ inputs.make_target }}
        run: make ${{ inputs.make_target }}
      - name: Publish release
        uses: eloquent/github-release-action@v3
        with:
          reactions: hooray,heart,rocket
